### ISSUE TITLE
Angular DataBinding is not working in xmd-step label

### ISSUE THREAD

**Issue by nsinha123** [oscar09/xmdWizard#3]
Hi

We are using xmd-wizard for the HTML page and in controller we are doing some operations. We are also translating the label field according to the configured language. So the code is -
 
```
<xmd-wizard active-step="currentStep" on-change="stepChanged()" on-save="savePath()">
<xmd-step label="{{translateData.GENERAL_INFORMATION}}" xmd-required="true"> //Not working
```
 
But the DataBinding is not working in the label field! But it's working in other places in the same HTML, for example -
 
```
<md-input-container flex="50" >
<label class="crudLabel">{{translateData.PATH}} {{translateData.NAME}}</label> //Working
</md-input-container>
```
 
So only within the label element of xmd-step, the DataBinding is not working!!!

Can you please look into this issue and provide a fix?

Thanks in advance.

**Comment by oscar09** [comment]
The issue should be fixed now, please test it with the latest changes.

**Comment by nsinha123** [comment]
Hi, the issue is now resolved. Thanks for the quick and earnest response.
